inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  RunRailsCops: true

  Include:
    - "**/*.gemspec"
    - "**/Rakefile"
    - "**/Gemfile"
    - "**/Vagrantfile"
    - "**/config.ru"
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"

