language: ruby

before_install:
  - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"

rvm:
  - "1.9.3"
before_script:
  - "mysql -e 'create database travis_testdb'"
  - "cp ./config/database_travis.yml ./config/database.yml"

script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/features

after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
