development:
  company_name: "Maryland Industrial Supply and Services Corp."
  address: "2150 Manansala Building M. Billones St. Bambang Pasig City 1600"
  contact_number: "Tel No : 661-6809 - Telefax : 571-9186"
  email_address: "Email: mlandcorp@gmail.com"
  logo: 'logo.png'

production:
  company_name: "Maryland Industrial Supply and Services Corp."
  address: "2150 Manansala Building M. Billones St. Bambang Pasig City 1600"
  contact_number: "Tel No : 661-6809 - Telefax : 571-9186"
  email_address: "Email: mlandcorp@gmail.com"
  logo: 'logo.png'

test:
  company_name: "Maryland Industrial Supply and Services Corp."
  address: "2150 Manansala Building M. Billones St. Bambang Pasig City 1600"
  contact_number: "Tel No : 661-6809 - Telefax : 571-9186"
  email_address: "Email: mlandcorp@gmail.com"
  logo: 'logo.png'
