development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  database: mlandcop_pos_test
  username: miku
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  username: deploy
  database: mlandcop_pos_production
  pool: 5
  timeout: 5000
